---
seq-len: 16
lr: 0.001
lr-decay: 2
lr-step: 10
early-stop: False
num-epochs: 100000
epoch-len: 200
train-proportion: 0.95
pc-embed-size: 64
page-embed-size: 256
offset-embed-size: 256000
mha-heads: 100
lstm-layers: 1
lstm-units: 256
dropout-rate: 0.2
batch-size: 8192
weight-decay: 0.0
rng-seed: 42
parallel: False
trace: "/mnt/data/ssd/yutong_data/heaptracer_text.mcf.1135483.0000.bin"
# trace: "stdin"
trace-metafile: "./processed.pkl"
trace-format: "basic"
save-interval: 2
outfile: "voyager.ckpt"
warmup: 0
loss: "globalaccess"
scheduler: "multistep" 
infer-out: "voyager-infer.bin"
flush-interval: 50000
online: true
gpuid: 0
cycle-skip: 3
predict-cycle-len: 6
line-bits: 12
offset-bits: 9
