---
seq-len: 16
lr: 0.001
lr-decay: 2
lr-step: 10
early-stop: False
num-epochs: 100000
epoch-len: 200
train-proportion: 0.95
pc-embed-size: 64
page-embed-size: 256
offset-embed-size: 256000
mha-heads: 100
lstm-layers: 1
lstm-units: 256
dropout-rate: 0.2
batch-size: 256
weight-decay: 0.0
rng-seed: 42
parallel: False
trace: "/mnt/data/ssd/yutong_data/heaptracer_text.mcf.1135483.0000.bin"
trace-metafile: "./processed.pkl"
trace-format: "multilabel"
save-interval: 10
outfile: "voyagerml.ckpt"
warmup: 0
loss: "multilabel"
scheduler: "multistep" 
infer-out: "voyagerml-infer.bin"
flush-interval: 250000
online: true
